### ISSUE TITLE
SshNet.Security.Cryptography doesn't load properly.

### ISSUE THREAD

**Issue by Abalalojik** [ArkEcosystem/ark-net#52]
SshNet.Security.Cryptography

says:

System.AggregateException
  HResult=0x80131500
  Message=Une ou plusieurs erreurs se sont produites.
  Source=mscorlib
  Arborescence des appels de procédure :
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   à System.Threading.Tasks.Task`1.get_Result()
   à ArkNet.Controller.AccountController.GetArkAccount() dans C:\Users\abala\source\repos\ark-net-master\ark-net\Controller\AccountController.cs :ligne 86
   à DevNetWallet.Form1.btn_importAddress_Click(Object sender, EventArgs e) dans C:\Users\abala\source\repos\DevNetWallet\DevNetWallet\Form1.cs :ligne 29
   à System.Windows.Forms.Control.OnClick(EventArgs e)
   à System.Windows.Forms.Button.OnClick(EventArgs e)
   à System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ButtonBase.WndProc(Message& m)
   à System.Windows.Forms.Button.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   à System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   à System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   à System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   à System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   à System.Windows.Forms.Application.Run(Form mainForm)
   à DevNetWallet.Program.Main() dans C:\Users\abala\source\repos\DevNetWallet\DevNetWallet\Program.cs :ligne 19

Exception interne 1 :
TypeInitializationException : Une exception a été levée par l'initialiseur de type pour 'ArkNet.Core.Crypto'.

Exception interne 2 :
FileLoadException : Impossible de charger le fichier ou l'assembly 'SshNet.Security.Cryptography, Version=1.3.0.0, Culture=neutral, PublicKeyToken=2fa9220ff3eadda4' ou une de ses dépendances. La définition trouvée du manifeste de l'assembly ne correspond pas à la référence de l'assembly. (Exception de HRESULT : 0x80131040)

**Comment by Abalalojik** [comment]
System.AggregateException
HResult=0x80131500
Message=One or more errors occured.
Source=mscorlib
Threshold of procedure calls :
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task1.get_Result()
at ArkNet.Controller.AccountController.GetArkAccount() dans C:\Users\abala\source\repos\ark-net-master\ark-net\Controller\AccountController.cs :line 86
at DevNetWallet.Form1.btn_importAddress_Click(Object sender, EventArgs e) in C:\Users\abala\source\repos\DevNetWallet\DevNetWallet\Form1.cs :line 29
at System.Windows.Forms.Control.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ButtonBase.WndProc(Message& m)
at System.Windows.Forms.Button.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
at
System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
at System.Windows.Forms.Application.Run(Form mainForm)
at DevNetWallet.Program.Main() dans C:\Users\abala\source\repos\DevNetWallet\DevNetWallet\Program.cs :ligne 19

Internal Exception 1 :
TypeInitializationException : An exception has been leveraged by the type initializer for  'ArkNet.Core.Crypto'.

Internal Exception 2 :
FileLoadException : Impossible to load the file or assembly 'SshNet.Security.Cryptography, Version=1.3.0.0, Culture=neutral, PublicKeyToken=2fa9220ff3eadda4' or one of its dependency. The assembly's manifest found doesn't correspond to the reference assembly. (Exception of HRESULT : 0x80131040)

**Comment by Abalalojik** [comment]
Here's the code that makes it happen:

```c#
using ArkNet;
using ArkNet.Controller;
using ArkNet.Utils.Enum;
using System;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DevNetWallet
{
    public partial class Form1 : Form
    {
        private ArkNetApi _arkNetApi;
        public ArkNetApi PArkNetApi => _arkNetApi ?? (_arkNetApi = new ArkNetApi());
        public Form1()
        {
            
            InitializeComponent();

            Task.Run(() => StartArkApi());
        }

        private async void StartArkApi()
        {
            await PArkNetApi.Start(NetworkType.DevNet);
        }
        private void btn_importAddress_Click(object sender, EventArgs e)
        {
            var accCtnrl = new AccountController(PArkNetApi, tb_passphrase.Text);
            lb_addresses.Items.Add(accCtnrl.GetArkAccount().Address);
        }
    }
}
```
